[package]
name = "img-organizer"
version = "0.1.0"
authors = ["Patric <patric.dexheimer@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
walkdir = "2.3.2"
chrono = "0.4"
kamadak-exif = "0.5.4"